<script>
// This is a tree-view that lists available elements that can be added to the UI being edited.
// Non-leaf nodes are collapsible and leaf nodes can be double-clicked or dragged onto the canvas.
// This list is generated by querying the editor server.
</script>



<style>

</style>
